name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # 每天 UTC 00:00 运行一次
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake.svg
            snake-dark.svg?palette=github-dark

      - name: Commit files
        uses: EndBug/add-and-commit@v9
        with:
          add: "snake.svg snake-dark.svg"
          message: "chore: update contribution snake"
